baseurl = "/"
title = "John's Thoughts"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = ""
    description = "Random thoughts, mostly my own."
    github = ""
    twitter = ""
    email = "john@johnstorey.org"
    opengraph = false
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"
    rss = true

[Permalinks]
    post = "/:filename/"
